name: Build and Test
on:
    push:
    pull_request:
concurrency:
    group: compile-${{ github.workflow }}-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    cancel-in-progress: true

jobs:
  compile:
    strategy:
      matrix:
#          node: [ '14', '18' ]
          node: [ '14' ] #can't run on 18
    runs-on: ubuntu-latest
    name: Build on Node ${{ matrix.node }}
    steps:
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: version check
        run: |
            npm -v
            node -v
            cat /home/runner/work/_temp/.npmrc

      - name: Install dependencies
        run: npm install  --prefer-offline --no-audit --ignore-scripts

      - name: rebuild and prepare
        run: npm rebuild && npm run prepare --if-present


      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

##Lint fails, skip
#      - name: Lint
#        run: npm run lint

      - name: setup Package
        run: |
            ls -ltr
            mkdir -p ./target/docs
            # cp -fr ./storybook-static ./target/docs
            cp -fr ./dist/* ./target/.

      - uses: actions/upload-artifact@v2
        with:
            name: Package
            path: ./target
